name: Upload to Artifact

on:
  push:
    branches:
      - main

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Pull Latest Changes
      run: git pull origin main

    - name: Upload Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: latest_keep_root
        path: https://github.com/ankitvrsharma/Keep-Root/blob/76ec9bc1b1e606dccb59d8dca6569dfba320d5bf/Keep_Root.sh
        
